dist: trusty
language: node_js
node_js:
 - '8'
before_install: .travis/before_install.sh
install:
  - npm install
script: lerna run lint
sudo: false
deploy:
  -
    provider: script
    script: "bash ./scripts/deploy.sh"
    skip_cleanup: true
    true:
      branch: master
  -
    allow-empty-commit: true
    email: carbon@us.ibm.com
    github-token: $GH_TOKEN
    keep-history: true
    local-dir: pages
    name: carbon-bot
    provider: pages
    skip_cleanup: true
    true:
      branch: master
notifications:
  email: false
